merge with launchpad

diff --git a/data/toriOSmenu b/data/toriOSmenu
--- a/data/toriOSmenu
+++ b/data/toriOSmenu
@@ -1,11 +1,25 @@
 #!/bin/bash
+## Live Menu
 #MANY thanks to Puppy!!!
 shopt -s nullglob
 MENUFILE=${HOME}/.config/torimenu
-TORIPDF=${HOME}/torios.pdf
+TORIMAN=/usr/share/doc/torios.pdf
 DD=/usr/share/desktop-directories
-rm ${MENUFILE}
-echo "replacing '$MENUFILE'"
+if [ -f "${MENUFILE}" ]
+then
+  rm ${MENUFILE}
+  echo "replacing '$MENUFILE'"
+fi
+if [ ! -d "${HOME}" ]
+then
+  echo "WARNING: Please set your HOME environment variable and re-run this"
+  exit 1
+fi
+if [ ! -d "${DD}" ]
+then
+  echo "You are missing the Desktop Directories.. you must install this program again"
+  exit 1
+fi
 {	#localization block
 [ $myLANG ] || myLANG=${LANGUAGE%% *}
 [ $myLANG ] || myLANG=${LANG%_*}
@@ -17,18 +31,22 @@ echo "replacing '$MENUFILE'"
 for DESKTOP_FILE in /usr/share/applications/*.desktop ; do
 	NAME="" ICON="" CATS="" EXEC="" LINE="" #prevent carryover from previous file
 	while read LINE || [ "$LINE" ]; do
+		#if [ "$LINE" == "[Desktop Action*" ]
+		#then
 		case $LINE in
 			Name?${myLANG%_*}?=*|Name=*) NAME="${LINE#*=}"'' ;; # sc0ttman... should use "Name[$myLANG]=" if found
+			'[Desktop Entry'*) continue ;;
 			TryExec=*|Exec=*) EXEC="${LINE#*=}"'' ;;
 			Categories=*) CATS="${LINE#*=}"'' ;;
 			Icon=*) ICON="${LINE#*=}"''  ;;
 			Terminal=*) TERM="${LINE#*=}"''  ;;
+			"["*) break ;; ##any other groups thanks to technosaurus
+			
 			# Comment=*|Comment?${LANG%_*}?=*) COMMENT="${LINE#*=}"''  ;; #jwm doesn't support tooltips on menu items yet ... uncomment this if it ever does
 		esac
+		#fi
 	done < $DESKTOP_FILE
 
-##TODO: Compare the icon filename... if it has an absolute path (i.e. /path/to/whatever.png) don't add .png
-#Also, need to check if the default Icons are svg or png
 if [ "${TERM}" == "true" ]
 then
 EXEC="x-terminal-emulator -e ${EXEC}"
@@ -36,14 +54,12 @@ fi
 
 if [[ "${ICON##*.}" == "xpm" ]] || [[ "${ICON##*.}" == "svg" ]] || [[ "${ICON##*.}" == "png" ]] || [[ "${ICON}" == "/*" ]]
 then
-	MenuEntry='<Program label="'${NAME}'" icon="'${ICON}'">'${EXEC%\ \%?}'</Program>
- '
+	MenuEntry='
+	<Program label="'${NAME}'" icon="'${ICON}'">'${EXEC%\ \%?}'</Program>'
 else
-	MenuEntry='<Program label="'${NAME}'" icon="'${ICON}'.svg">'${EXEC%\ \%?}'</Program>
- '
+	MenuEntry='
+	<Program label="'${NAME}'" icon="'${ICON}'.svg">'${EXEC%\ \%?}'</Program>'
 fi
-
-##Need to check if Terminal=true also...
 
 #	[ "${EXEC}" ] && MenuEntry='<Program label="'${NAME}'" icon="'${ICON}'.svg">'${EXEC%\ \%?}'</Program> '
 	#CATS="${CATS%;*}" # sc0ttman, keep just the first (or only) category.. everything before the semi-colon ;...no we may want multiple entries?
@@ -66,13 +82,6 @@ fi
 	done
 done
 }
-for MENU_NAME in ${DD}/jwm-appl* ; do
-	while read NAME_LINE || [ "$NAME_LINE" ]; do
-		case $NAME_LINE in
-			Name?${myLANG%_*}?=*|Name=*) NAME_NAME="${NAME_LINE#*=}"'';;
-		esac
-	done < $MENU_NAME
-done
 for MENU_A in ${DD}/jwm-accessories* ; do
 	A_NAME="" A_ICON="" A_LINE="" #prevent carryover from previous file
 	while read A_LINE || [ "$A_LINE" ]; do
@@ -242,17 +251,33 @@ MENU=''${MENU}'
 </Menu>'
 fi
 }
-{	#Add the header and footer to the Menu
-MENU='<?xml version="1.0"?><JWM>
-<!-- generated by '$0' -->
-    <RootMenu height="0" onroot="5" label="'${NAME_NAME}'">
+## check for the ToriOS pdf file... if it exists do this
+if [ -f "${TORIPDF}" ]
+then
+{
+MENU='<?xml version="1.0"?>
+<JWM>
+<!-- generated by '$PWD'/'$0' -->
+    <RootMenu height="0" onroot="5">
 '"$MENU"'
         <Separator/>
-	<Program label="ToriOS Manual" icon="help-faq.svg">xpdf -title "ToriOS Manual" -cont '${TORIPDF}'</Program>
-        <Program icon="system-shutdown.svg" label="Quit">jwm-settings-manager --halt</Program>
+	<Program label="ToriOS Manual" icon="help-faq.svg">xdg-open '${TORIMAN}'</Program>
     </RootMenu></JWM>'
 }
+else
+{
+## basically if this isn't Tori OS don't link to our manual :)
+MENU='<?xml version="1.0"?>
+<JWM>
+<!-- generated by '$PWD'/'$0' -->
+    <RootMenu height="0" onroot="5">
+'"$MENU"'
+    </RootMenu></JWM>'
+}
+fi
 echo "$MENU" >> ${MENUFILE}
 sed -i 's/&/&amp;/g' ${MENUFILE}
-echo "Done!"
-jwm -reload
+RESULT=$(jwm -reload)
+echo "Done!
+$RESULT"
+
